package Entidad;
// Generated 9/08/2025 01:43:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Carrera generated by hbm2java
 */
public class Carrera  implements java.io.Serializable {


     private int codigo;
     private String nombre;
     private Set<Alumno> alumnos = new HashSet<Alumno>(0);

    public Carrera() {
    }

	
    public Carrera(int codigo) {
        this.codigo = codigo;
    }
    public Carrera(int codigo, String nombre, Set<Alumno> alumnos) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.alumnos = alumnos;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Alumno> getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Set<Alumno> alumnos) {
        this.alumnos = alumnos;
    }




}


